package pl.zara.tests;

import pl.zara.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Cookies label check")
    void generatedTest() {
        step("Open url https://www.zara.com/pl/", () -> {
            open("https://www.zara.com/pl/");
        });

        step("check if there is label \"Akceptuj wszystkie pliki cookie\"", () -> {
            $("#onetrust-accept-btn-handler ").shouldHave(text("Akceptuj wszystkie pliki cookie"));
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.zara.com/pl/'", () ->
                open("https://www.zara.com/pl/"));

        step("Page title should have text 'ZARA Polska / Poland | WYPRZEDAŻ'", () -> {
            String expectedTitle = "ZARA Polska / Poland | WYPRZEDAŻ";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.zara.com/pl/'", () ->
                open("https://www.zara.com/pl/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}